### ISSUE TITLE
Failed to run the task

### ISSUE THREAD

**Issue by RonDaha** [cermak-petr/act-anti-captcha-recaptcha#1]
Hey, I tried to run the actor task but received this error - 

```
2020-11-25T21:53:05.722Z User function threw an exception:
2020-11-25T21:53:05.723Z Account authorization key not found in the system
```
Any ideas what could it be?

**Comment by pocesar** [comment]
are you running on the platform or locally?

**Comment by RonDaha** [comment]
Same error on both ends. I just funded money into my recapcha2 account.
Should I wait for a while?

**Comment by pocesar** [comment]
contact me on Intercom on apify.com so I can take a look
